# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9b59cd4baea4d22c02314cb231215997d94dec07639b936512d59e0e23f3a01e425bbeb0cfd7f4e0fbb74133b312a77ddcb208e873e9d7961dd0d12c69f0314

test:
  secret_key_base: aa6d249caac1cf527ee5d44d216e291dac88dc686a0eef3f467b41c141b87bfaf1cdc516e68e1121ff770aee9135a65cb10a8ceaf1f53fae9e81f424adfedc43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
